version: "3.5"

services:
  web:
    image: web
    container_name: web
    tty: true
    build:
      context: requirements
    ports:
      - '8000:8000'
    env_file:
      - requirements/.env
    restart: always
    networks:
      - ft_transcendence
    depends_on:
      - postgres
    command: ["bash", "start.sh", "[::]:8000"]

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    networks:
      - ft_transcendence
    env_file:
      - requirements/.env

volumes:
  db:
    driver: local
    name: postgres
    driver_opts:
      type: none
      o: bind
      device: ./.temp/data/postgres

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
