version: "3.5"

services:
  web:
    image: web
    container_name: web
    tty: true
    build:
      context: requirements
    ports:
      - '8000:8000'
    env_file:
      - requirements/.env
    restart: always
    networks:
      - ft_transcendence
    depends_on:
      - postgres
    command: ["bash", "start.sh", "[::]:8000"]

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    networks:
      - ft_transcendence
    env_file:
      - requirements/.env

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - '9100:9100'
    networks:
      - ft_transcendence

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    restart: unless-stopped
    networks:
      - ft_transcendence

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    env_file:
      - requirements/.env
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      # wget https://raw.githubusercontent.com/grafana/grafana/main/conf/defaults.ini -O grafana/grafana.ini
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    links:
      - prometheus
    networks:
      - ft_transcendence

volumes:
  db:
    driver: local
    name: postgres
    driver_opts:
      type: none
      o: bind
      device: /home/alcatraz/data/postgres

  prom_data: {}


networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
