# Generated by Django 5.0.2 on 2024-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('game_creator', models.CharField(max_length=100)),
                ('game_opponent', models.CharField(blank=True, max_length=100, null=True)),
                ('is_over', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
