global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets: [ "web:8000" ]
    relabel_configs:
      - source_labels: [ __adress__]
        target_label: instance
        regex: "([^:]+):\\d+"
